version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meta-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: uber-db
    ports:
      - "5433:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"