# Setarile de conectare la PostgreSQL-ul din Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/uber-db
spring.datasource.username=user
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect